import type { Permission } from "@/tenant/types";

export const SYSTEM_PERMISSIONS: Permission[] = [
  {
    id: "perm-organization-read",
    key: "organization:read",
    resource: "organization",
    action: "read",
    description: "Visualizzare i dati dell'organizzazione",
    scope: "organization",
  },
  {
    id: "perm-organization-manage",
    key: "organization:manage",
    resource: "organization",
    action: "manage",
    description: "Gestire impostazioni e configurazione organizzazione",
    scope: "organization",
  },
  {
    id: "perm-workspace-read",
    key: "workspace:read",
    resource: "workspace",
    action: "read",
    description: "Visualizzare workspace",
    scope: "workspace",
  },
  {
    id: "perm-workspace-manage",
    key: "workspace:manage",
    resource: "workspace",
    action: "manage",
    description: "Creare e gestire workspace",
    scope: "workspace",
  },
  {
    id: "perm-membership-read",
    key: "membership:read",
    resource: "membership",
    action: "read",
    description: "Visualizzare membri e inviti",
    scope: "organization",
  },
  {
    id: "perm-membership-manage",
    key: "membership:manage",
    resource: "membership",
    action: "manage",
    description: "Invitare, assegnare ruoli e gestire membri",
    scope: "organization",
  },
  {
    id: "perm-clienti-read",
    key: "clienti:read",
    resource: "clienti",
    action: "read",
    description: "Visualizzare clienti",
    scope: "workspace",
  },
  {
    id: "perm-clienti-write",
    key: "clienti:write",
    resource: "clienti",
    action: "write",
    description: "Creare e modificare clienti",
    scope: "workspace",
  },
  {
    id: "perm-clienti-delete",
    key: "clienti:delete",
    resource: "clienti",
    action: "delete",
    description: "Eliminare clienti",
    scope: "workspace",
  },
  {
    id: "perm-tour-read",
    key: "tour:read",
    resource: "tour",
    action: "read",
    description: "Visualizzare tour e partecipazioni",
    scope: "workspace",
  },
  {
    id: "perm-tour-write",
    key: "tour:write",
    resource: "tour",
    action: "write",
    description: "Creare e modificare tour",
    scope: "workspace",
  },
  {
    id: "perm-tour-delete",
    key: "tour:delete",
    resource: "tour",
    action: "delete",
    description: "Eliminare tour",
    scope: "workspace",
  },
  {
    id: "perm-pagamenti-read",
    key: "pagamenti:read",
    resource: "pagamenti",
    action: "read",
    description: "Visualizzare pagamenti",
    scope: "workspace",
  },
  {
    id: "perm-pagamenti-write",
    key: "pagamenti:write",
    resource: "pagamenti",
    action: "write",
    description: "Registrare e modificare pagamenti",
    scope: "workspace",
  },
  {
    id: "perm-comunicazioni-read",
    key: "comunicazioni:read",
    resource: "comunicazioni",
    action: "read",
    description: "Visualizzare comunicazioni",
    scope: "workspace",
  },
  {
    id: "perm-comunicazioni-write",
    key: "comunicazioni:write",
    resource: "comunicazioni",
    action: "write",
    description: "Inviare e gestire comunicazioni",
    scope: "workspace",
  },
  {
    id: "perm-dashboard-read",
    key: "dashboard:read",
    resource: "dashboard",
    action: "read",
    description: "Visualizzare dashboard e KPI",
    scope: "workspace",
  },
  {
    id: "perm-settings-read",
    key: "settings:read",
    resource: "settings",
    action: "read",
    description: "Visualizzare impostazioni workspace",
    scope: "workspace",
  },
  {
    id: "perm-settings-manage",
    key: "settings:manage",
    resource: "settings",
    action: "manage",
    description: "Modificare impostazioni workspace",
    scope: "workspace",
  },
  {
    id: "perm-audit-read",
    key: "audit:read",
    resource: "audit",
    action: "read",
    description: "Visualizzare registro attività",
    scope: "workspace",
  },
  {
    id: "perm-automazioni-read",
    key: "automazioni:read",
    resource: "automazioni",
    action: "read",
    description: "Visualizzare automazioni",
    scope: "workspace",
  },
  {
    id: "perm-automazioni-manage",
    key: "automazioni:manage",
    resource: "automazioni",
    action: "manage",
    description: "Configurare automazioni",
    scope: "workspace",
  },
];

export const PERMISSION_BY_KEY = new Map(
  SYSTEM_PERMISSIONS.map((permission) => [permission.key, permission]),
);

export const PERMISSION_BY_ID = new Map(
  SYSTEM_PERMISSIONS.map((permission) => [permission.id, permission]),
);
